// Mock data in the format of Google Places API search response
// Reference: https://developers.google.com/maps/documentation/places/web-service/search

export type MockPlaceResult = {
  place_id: string;
  name: string;
  types: string[];
  formatted_address: string;
  geometry: {
    location: { lat: number; lng: number };
  };
  rating: number;
  user_ratings_total: number;
  opening_hours: { open_now: boolean };
  photos: { photo_reference: string }[];
  icon: string;
  business_status: string;
  description: string;
};

export const mockSearchResults = {
  results: [
    {
      place_id: '4',
      name: 'Akihabara Arcade and Bar',
      types: ['bar', 'night_club', 'point_of_interest', 'establishment'],
      formatted_address: '1232 E Colfax Ave, Denver, CO 80218',
      geometry: {
        location: { lat: 39.7392, lng: -104.979 },
      },
      rating: 4.6,
      user_ratings_total: 210,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo4' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png',
      business_status: 'OPERATIONAL',
      description: 'Japanese-themed arcade bar with retro games, cocktails, and anime nights.',
    },
    {
      place_id: '5',
      name: "Thane's Table",
      types: ['bar', 'board_game_store', 'point_of_interest', 'establishment'],
      formatted_address: '7525 W 44th Ave, Wheat Ridge, CO 80033',
      geometry: {
        location: { lat: 39.7765, lng: -105.082 },
      },
      rating: 4.8,
      user_ratings_total: 320,
      opening_hours: { open_now: false },
      photos: [{ photo_reference: 'photo5' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png',
      business_status: 'OPERATIONAL',
      description: 'Board game bar with hundreds of games, craft beer, and weekly events.',
    },
    {
      place_id: '6',
      name: 'Escapology Escape Rooms Denver',
      types: ['amusement_park', 'point_of_interest', 'establishment'],
      formatted_address: '2223 S Monaco Pkwy, Denver, CO 80222',
      geometry: {
        location: { lat: 39.6766, lng: -104.913 },
      },
      rating: 4.7,
      user_ratings_total: 150,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo6' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/amusement-71.png',
      business_status: 'OPERATIONAL',
      description: 'Escape room venue with multiple themed adventures and private bookings.',
    },
    {
      place_id: '7',
      name: 'Denver Escape Room',
      types: ['amusement_park', 'point_of_interest', 'establishment'],
      formatted_address: '11674 Huron St #300, Northglenn, CO 80234',
      geometry: {
        location: { lat: 39.9116, lng: -104.996 },
      },
      rating: 4.9,
      user_ratings_total: 200,
      opening_hours: { open_now: false },
      photos: [{ photo_reference: 'photo7' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/amusement-71.png',
      business_status: 'OPERATIONAL',
      description: 'Highly-rated escape room with challenging puzzles and immersive experiences.',
    },
    {
      place_id: '8',
      name: 'Solutions Lounge & Restaurant featuring Escapology',
      types: ['restaurant', 'bar', 'amusement_park', 'point_of_interest', 'establishment'],
      formatted_address: '2223 S Monaco Pkwy, Denver, CO 80222',
      geometry: {
        location: { lat: 39.6766, lng: -104.913 },
      },
      rating: 4.6,
      user_ratings_total: 180,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo8' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/restaurant-71.png',
      business_status: 'OPERATIONAL',
      description: 'Escape room venue with a full restaurant and bar, perfect for group outings.',
    },
    {
      place_id: '9',
      name: 'The Infinite Monkey Theorem',
      types: ['bar', 'food', 'point_of_interest', 'establishment'],
      formatted_address: '3200 Larimer St, Denver, CO 80205',
      geometry: {
        location: { lat: 39.7645, lng: -104.98 },
      },
      rating: 4.5,
      user_ratings_total: 250,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo9' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png',
      business_status: 'OPERATIONAL',
      description: 'Urban winery with a funky tasting room and local events.',
    },
    {
      place_id: '10',
      name: 'Board Game Republic',
      types: ['bar', 'board_game_store', 'point_of_interest', 'establishment'],
      formatted_address: '900 W 1st Ave, Denver, CO 80223',
      geometry: {
        location: { lat: 39.7156, lng: -104.999 },
      },
      rating: 4.7,
      user_ratings_total: 175,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo10' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png',
      business_status: 'OPERATIONAL',
      description: 'Board game bar with a huge library, food, drinks, and friendly staff.',
    },
    {
      place_id: '11',
      name: 'Room5280 Escape Room',
      types: ['amusement_park', 'point_of_interest', 'establishment'],
      formatted_address: '142 W 12th Ave, Denver, CO 80204',
      geometry: {
        location: { lat: 39.7362, lng: -104.991 },
      },
      rating: 4.8,
      user_ratings_total: 120,
      opening_hours: { open_now: false },
      photos: [{ photo_reference: 'photo11' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/amusement-71.png',
      business_status: 'OPERATIONAL',
      description: 'Escape room with creative puzzles and immersive storylines.',
    },
    {
      place_id: '12',
      name: 'Puzzah! Escape Rooms',
      types: ['amusement_park', 'point_of_interest', 'establishment'],
      formatted_address: '1441 W 104th Ave, Denver, CO 80234',
      geometry: {
        location: { lat: 39.8856, lng: -105.008 },
      },
      rating: 4.6,
      user_ratings_total: 110,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo12' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/amusement-71.png',
      business_status: 'OPERATIONAL',
      description: 'Escape room venue with tech-driven puzzles and multiple game themes.',
    },
    {
      place_id: '13',
      name: 'The 1up Arcade Bar - Colfax',
      types: ['bar', 'night_club', 'point_of_interest', 'establishment'],
      formatted_address: '717 E Colfax Ave, Denver, CO 80203',
      geometry: {
        location: { lat: 39.7405, lng: -104.977 },
      },
      rating: 4.6,
      user_ratings_total: 400,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo13' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png',
      business_status: 'OPERATIONAL',
      description: 'Arcade bar with classic games, pinball, and a lively atmosphere.',
    },
    {
      place_id: '14',
      name: 'The Tabletop Tap',
      types: ['bar', 'board_game_store', 'point_of_interest', 'establishment'],
      formatted_address: '2239 E Colfax Ave, Denver, CO 80206',
      geometry: { location: { lat: 39.7401, lng: -104.956 } },
      rating: 4.7,
      user_ratings_total: 180,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo14' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png',
      business_status: 'OPERATIONAL',
      description: 'Board game bar with local brews and a huge game library.',
    },
    {
      place_id: '15',
      name: 'Grandma’s House',
      types: ['bar', 'brewery', 'point_of_interest', 'establishment'],
      formatted_address: '1710 S Broadway, Denver, CO 80210',
      geometry: { location: { lat: 39.6867, lng: -104.987 } },
      rating: 4.6,
      user_ratings_total: 210,
      opening_hours: { open_now: false },
      photos: [{ photo_reference: 'photo15' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png',
      business_status: 'OPERATIONAL',
      description: 'Craft brewery with board games, quirky decor, and events.',
    },
    {
      place_id: '16',
      name: 'The Magic Lantern',
      types: ['bar', 'arcade', 'point_of_interest', 'establishment'],
      formatted_address: '925 W 8th Ave, Denver, CO 80204',
      geometry: { location: { lat: 39.7292, lng: -105.004 } },
      rating: 4.5,
      user_ratings_total: 120,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo16' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png',
      business_status: 'OPERATIONAL',
      description: 'Retro arcade bar with pinball, classic games, and cocktails.',
    },
    {
      place_id: '17',
      name: 'EscapeWorks Denver',
      types: ['amusement_park', 'point_of_interest', 'establishment'],
      formatted_address: '1529 Champa St, Denver, CO 80202',
      geometry: { location: { lat: 39.7466, lng: -104.995 } },
      rating: 4.8,
      user_ratings_total: 250,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo17' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/amusement-71.png',
      business_status: 'OPERATIONAL',
      description: 'Escape room venue with challenging puzzles and immersive themes.',
    },
    {
      place_id: '18',
      name: 'The Board Game Barrister',
      types: ['board_game_store', 'point_of_interest', 'establishment'],
      formatted_address: '3455 S University Blvd, Englewood, CO 80113',
      geometry: { location: { lat: 39.6543, lng: -104.959 } },
      rating: 4.9,
      user_ratings_total: 90,
      opening_hours: { open_now: false },
      photos: [{ photo_reference: 'photo18' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/shopping-71.png',
      business_status: 'OPERATIONAL',
      description: 'Board game shop with weekly game nights and tournaments.',
    },
    {
      place_id: '19',
      name: 'The Enigma Room',
      types: ['amusement_park', 'point_of_interest', 'establishment'],
      formatted_address: '1201 Santa Fe Dr, Denver, CO 80204',
      geometry: { location: { lat: 39.7342, lng: -104.997 } },
      rating: 4.7,
      user_ratings_total: 130,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo19' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/amusement-71.png',
      business_status: 'OPERATIONAL',
      description: 'Escape room with mysterious puzzles and creative storylines.',
    },
    {
      place_id: '20',
      name: 'The Dice Den',
      types: ['bar', 'board_game_store', 'point_of_interest', 'establishment'],
      formatted_address: '800 E 26th Ave, Denver, CO 80205',
      geometry: { location: { lat: 39.7592, lng: -104.977 } },
      rating: 4.6,
      user_ratings_total: 110,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo20' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png',
      business_status: 'OPERATIONAL',
      description: 'Bar and board game lounge with snacks and local brews.',
    },
    {
      place_id: '21',
      name: 'Puzzle Palace',
      types: ['amusement_park', 'point_of_interest', 'establishment'],
      formatted_address: '1010 15th St, Denver, CO 80202',
      geometry: { location: { lat: 39.7472, lng: -104.995 } },
      rating: 4.8,
      user_ratings_total: 160,
      opening_hours: { open_now: false },
      photos: [{ photo_reference: 'photo21' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/amusement-71.png',
      business_status: 'OPERATIONAL',
      description: 'Escape room venue with a variety of puzzle adventures.',
    },
    {
      place_id: '22',
      name: 'Meeple’s Corner',
      types: ['bar', 'board_game_store', 'point_of_interest', 'establishment'],
      formatted_address: '2222 S Broadway, Denver, CO 80210',
      geometry: { location: { lat: 39.6822, lng: -104.987 } },
      rating: 4.7,
      user_ratings_total: 140,
      opening_hours: { open_now: true },
      photos: [{ photo_reference: 'photo22' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/bar-71.png',
      business_status: 'OPERATIONAL',
      description: 'Board game bar with a friendly atmosphere and game nights.',
    },
    {
      place_id: '23',
      name: 'The Vault Escape Room',
      types: ['amusement_park', 'point_of_interest', 'establishment'],
      formatted_address: '555 17th St, Denver, CO 80202',
      geometry: { location: { lat: 39.7478, lng: -104.99 } },
      rating: 4.9,
      user_ratings_total: 100,
      opening_hours: { open_now: false },
      photos: [{ photo_reference: 'photo23' }],
      icon: 'https://maps.gstatic.com/mapfiles/place_api/icons/amusement-71.png',
      business_status: 'OPERATIONAL',
      description: 'Escape room with bank heist and mystery themes.',
    },
    // ...add more mock places as needed, following Google Places API format
  ],
  status: 'OK',
};
